name: DartDex
description: A Pokédex entirely made with AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.13.0
  angular_forms: ^2.0.0
  angular_router: 2.0.0-alpha+19
  http: ^0.11.0

dev_dependencies:
  build_runner: ^1.6.5
  build_web_compilers: ^2.1.5
