name: DartDex
description: A Pokédex entirely made with AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.12.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.11.0
  stream_transform: ^0.0.6

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.0
